#!/bin/bash
mkdir /judge
cd /judge
curl -L https://github.com/DMOJ/judge/archive/master.tar.gz | tar -xz --strip-components=1
pip3 install -e .
. ~judge/.profile
runuser -u judge -w PATH -- dmoj-autoconf -V
