#!/bin/bash
mkdir /judge
cd /judge || exit
curl -L https://github.com/DMOJ/judge/archive/master.tar.gz | tar -xz --strip-components=1
pip3 install -e .
runuser -u judge -w PATH -- bash -c '. ~/.profile; python3 -u .docker.test.py'
