#!/bin/bash
mkdir /judge
cd /judge || exit
curl -L https://github.com/DMOJ/judge-server/archive/master.tar.gz | tar -xz --strip-components=1
python3 -m venv --prompt=DMOJ env
env/bin/pip3 install -e .
runuser -u judge -w PATH -- bash -c '. ~/.profile; /judge/env/bin/python3 -u .docker.test.py'
