name: Build Docker Images
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  amd64:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build tier 1 Docker image
      run: make TAG=amd64-latest image-tier1
    - name: Test tier 1 Docker image
      run: make TAG=amd64-latest test-tier1
    - name: Build tier 2 Docker image
      run: make TAG=amd64-latest image-tier2
    - name: Test tier 2 Docker image
      run: make TAG=amd64-latest test-tier2
    - name: Build tier 3 Docker image
      run: make TAG=amd64-latest image-tier3
    - name: Test tier 3 Docker image
      run: make TAG=amd64-latest test-tier3
    - name: Push images to Docker
      if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        docker push dmoj/runtimes-tier1:amd64-latest
        docker push dmoj/runtimes-tier2:amd64-latest
        docker push dmoj/runtimes-tier3:amd64-latest
        docker run -v "$(pwd)":/code mplatform/manifest-tool \
          --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD" \
          push from-spec /code/tier1/manifest.yml
        docker run -v "$(pwd)":/code mplatform/manifest-tool \
          --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD" \
          push from-spec /code/tier2/manifest.yml
        docker run -v "$(pwd)":/code mplatform/manifest-tool \
          --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD" \
          push from-spec /code/tier3/manifest.yml
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push images to GitHub Containers
      if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
      run: |
        echo "$CR_PAT" | docker login ghcr.io -u "$CR_USER" --password-stdin
        docker push ghcr.io/dmoj/runtimes-tier1:amd64-latest
        docker push ghcr.io/dmoj/runtimes-tier2:amd64-latest
        docker push ghcr.io/dmoj/runtimes-tier3:amd64-latest
      env:
        CR_USER: ${{ secrets.CR_USER }}
        CR_PAT: ${{ secrets.CR_PAT }}

  arm64:
    permissions:
      packages: write
    runs-on: [self-hosted, Linux, ARM64]
    steps:
    - uses: actions/checkout@v1
    - name: Build tier 1 Docker image
      run: make TAG=aarch64-latest image-tier1
    - name: Test tier 1 Docker image
      run: make TAG=aarch64-latest test-tier1
    - name: Build tier 2 Docker image
      run: make TAG=aarch64-latest image-tier2
    - name: Test tier 2 Docker image
      run: make TAG=aarch64-latest test-tier2
    - name: Build tier 3 Docker image
      run: make TAG=aarch64-latest image-tier3
    - name: Test tier 3 Docker image
      run: make TAG=aarch64-latest test-tier3
    - name: Push images to Docker
      if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        docker push dmoj/runtimes-tier1:aarch64-latest
        docker push dmoj/runtimes-tier2:aarch64-latest
        docker push dmoj/runtimes-tier3:aarch64-latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push images to GitHub Containers
      if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
      run: |
        echo "$CR_PAT" | docker login ghcr.io -u "$CR_USER" --password-stdin
        docker push ghcr.io/dmoj/runtimes-tier1:aarch64-latest
        docker push ghcr.io/dmoj/runtimes-tier2:aarch64-latest
        docker push ghcr.io/dmoj/runtimes-tier3:aarch64-latest
      env:
        CR_USER: ${{ secrets.CR_USER }}
        CR_PAT: ${{ secrets.CR_PAT }}
