name: Build Docker Images
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    permissions:
      packages: write
    strategy:
      matrix:
        arch:
          - tag: amd64-latest
            runner: ubuntu-latest
          - tag: aarch64-latest
            runner: [self-hosted, Linux, ARM64]
    runs-on: ${{ matrix.arch.runner }}
    steps:
    - uses: actions/checkout@v2
    - name: Build tier 1 Docker image
      run: make TAG=${{ matrix.arch.tag }} image-tier1
    - name: Test tier 1 Docker image
      run: make TAG=${{ matrix.arch.tag }} test-tier1
    - name: Build tier 2 Docker image
      run: make TAG=${{ matrix.arch.tag }} image-tier2
    - name: Test tier 2 Docker image
      run: make TAG=${{ matrix.arch.tag }} test-tier2
    - name: Build tier 3 Docker image
      run: make TAG=${{ matrix.arch.tag }} image-tier3
    - name: Test tier 3 Docker image
      run: make TAG=${{ matrix.arch.tag }} test-tier3
    - name: Push images to Docker
      if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        docker push dmoj/runtimes-tier1:${{ matrix.arch.tag }}
        docker push dmoj/runtimes-tier2:${{ matrix.arch.tag }}
        docker push dmoj/runtimes-tier3:${{ matrix.arch.tag }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push images to GitHub Containers
      if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
      run: |
        echo "$CR_PAT" | docker login ghcr.io -u "$CR_USER" --password-stdin
        docker push ghcr.io/dmoj/runtimes-tier1:${{ matrix.arch.tag }}
        docker push ghcr.io/dmoj/runtimes-tier2:${{ matrix.arch.tag }}
        docker push ghcr.io/dmoj/runtimes-tier3:${{ matrix.arch.tag }}
      env:
        CR_USER: ${{ secrets.CR_USER }}
        CR_PAT: ${{ secrets.CR_PAT }}

  manifest:
    if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Docker Hub Manifests
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        for tier in tier{1..3}; do
          args=()
          for arch in amd64 aarch64; do
            args+=(--amend "dmoj/runtimes-$tier:$arch-latest")
          done
          docker manifest create "dmoj/runtimes-$tier:latest" "${args[@]}"
          docker manifest push "dmoj/runtimes-$tier:latest"
        done
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
