name: Build Docker Images
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Images
      run: make all test TAG="$(branch="$(echo "$GITHUB_REF" | cut -d/ -f3-)"; case "$branch"  in master) echo latest;; *) echo "$branch";; esac)"
